# authenticate
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "Johnnyboy",
    "password": "P@ssw0rd!"
}

###

# create user account

POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "bob@jones.com",
    "password": "P@ssw0rd!",
    "role": "OWNER"
}

###

#authenticate new user

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "bob@jones.com",
    "password": "P@ssw0rd!"
}

###

@base_url = http://localhost:8080/api/contact-info

###

# Returns contact info associated with user id
GET {{base_url}}/user/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcml0dGVyLXNpdHRlciIsInN1YiI6IkpvaG5ueWJveSIsImF1dGhvcml0aWVzIjoiT1dORVIiLCJleHAiOjE2OTIzMDIzNDN9.OI1HnKVw-c7vUNebqKl-kFTUdEOvNN5OHXaLeLLPLG4

###

# should return contact info by id
GET {{base_url}}/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcml0dGVyLXNpdHRlciIsInN1YiI6IkpvaG5ueWJveSIsImF1dGhvcml0aWVzIjoiT1dORVIiLCJleHAiOjE2OTIzMDIzNDN9.OI1HnKVw-c7vUNebqKl-kFTUdEOvNN5OHXaLeLLPLG4

###

# should make new pet
POST {{base_url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2xhci1mYXJtIiwic3ViIjoiSm9obm55Ym95IiwiYXV0aG9yaXRpZXMiOiJPV05FUiIsImV4cCI6MTY5MjI5NjQzN30.Z7D-pTxJsMgQMH1ApoWVMcS1XtZMpnhURDfPBswjf0Q

{
  "name": "Prancer",
  "notes": "Very fast",
  "petType": "Llama",
  "goesWalking": true,
  "ownerId": 1
}

###

#should update by petId
PUT {{base_url}}/pet/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2xhci1mYXJtIiwic3ViIjoiSm9obm55Ym95IiwiYXV0aG9yaXRpZXMiOiJPV05FUiIsImV4cCI6MTY5MjIxOTM0N30.IelToxD7QN2LZasUX6MUt2vkGvIjcUlmAuULMfDhoZI

{
  "petId": 4,
  "name": "Prancer",
  "notes": "Very fast",
  "petType": "Tarantula",
  "goesWalking": true,
  "ownerId": 1
}


###

# should delete pet by id
DELETE {{base_url}}/pet/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2xhci1mYXJtIiwic3ViIjoiSm9obm55Ym95IiwiYXV0aG9yaXRpZXMiOiJPV05FUiIsImV4cCI6MTY5MjIxOTM0N30.IelToxD7QN2LZasUX6MUt2vkGvIjcUlmAuULMfDhoZI
###