# authenticate
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "Johnnyboy",
    "password": "P@ssw0rd!"
}

###

@base_url = http://localhost:8080/api/users

@bearer_token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcml0dGVyLXNpdHRlciIsInN1YiI6IkpvaG5ueWJveSIsImF1dGhvcml0aWVzIjoiT1dORVIiLCJleHAiOjE2OTI4NDA0ODR9.QQZuophsdV-ke4gCkIdPImNzViDZE5Hf_HuCa3hG8tw
###

# Get all owners
GET {{base_url}}/all-owners HTTP/1.1
Authorization: Bearer {{bearer_token}}

###

###

# Get all sitters
GET {{base_url}}/all-sitters HTTP/1.1
Authorization: Bearer {{bearer_token}}

###

# Get all sitters
GET {{base_url}}/owner/Johnnyboy HTTP/1.1
Authorization: Bearer {{bearer_token}}

###

# Get all sitters
GET {{base_url}}/sitter/DogBuddy HTTP/1.1
Authorization: Bearer {{bearer_token}}

###